:description: This site contains notes, information, blog posts, and other tidbits about my life.

= Zane Schaffer

This site contains notes, information, blog posts, and other tidbits about my life. You may contact me
via mailto:znschaffer@gmail.com[email] or any social media platform you see fit.


== Life Facts!

- I am a twenty-seven year old computer science student at https://northseattle.edu[North Seattle
College].

- I was born in Seattle, grew up in Bellevue, and have link:travels[lived in many
places]!

- I have been writing and producing music for most of my adult life. You can learn more about my musical endeavours link:music[here].

- I enjoy working on link:projects[projects] and learning new skills.

- My partner, https://xinrui.work[Xinrui], is an extremely talented and lovely individual

== Whats Going On Now?

Currently, I live on Capitol Hill, Seattle, Washington with Xinrui and our cat
Cleo. I spend a lot of time learning about programming language design, studying 
higher level math and calculus, researching self-hosted projects, and making noises
on my synths.

I'm building a real-time chat and drawing app with Xinrui to advance my knowledge
of web sockets and different networking protocols. It's going great!

A lot of my current time is taken up by the _pursuit of education_ I am subjecting myself to.
I've gone self-taught for most everything in computer science but enough is enough! Through this 
process, I have discovered an odd, but intriguing appreciation for mathematics I did not possess before.
Luckily, audio programming and it's related domains expect you to be fascinated with mathematics.
