name: convert via pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: convert markdown to html
        uses: docker://pandoc/latex:2.9
        with:
          args: -c "mkdir out; cd src;find src -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o ../out/${0%.md}.html' {} \;"          

      - name: check file system
        run: |
         "ls ."
         
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
                        
