name: convert via pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: setup output dir and copy images
        run: mkdir out; cp -r src/img out/; cp src/*.css out/ cp src/fonts out/;
      - name: convert markdown to html
        uses: docker://pandoc/core:edge
        with:
          entrypoint: /bin/sh
          args: -c "cd src; find . -iname '*.md' -type f -exec sh -c 'pandoc -f markdown -t html5 -c normalize.css -c concrete.css -s ${0} -o ../out/${0%.md}.html' {} \;"          
      - run: tree
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: znschaffer.com
                        
